place = input("Enter a random place: ")
cret = input("Enter a random creature: ")
obj = input("Enter a random object (plural): ")
building = input("Enter a random building: ")
person = input("Enter a random person: ")

print("\nThis morning in " + place + ",")
print("A man-eating " + cret + " was spotted causing chaos.")
print("It was chasing pedestrians with " + obj + "." )
print("It burned down the " + building + " to everyone's surprise")
print("It ran away once it saw " + person + " , who saved the day!")